version: 0.0
os: linux
files:
  - source: /dist/sample-angular-app/*
    destination: /var/www/html
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/html
    pattern: "**/*"
    owner: ec2-user
    group: ec2-user
AfterInstall:
    - location: change_location.sh
      timeout: 300
      runas: root